artifacts_config: 
  # Directory where all artifacts (outputs, models, logs) will be stored
  artifacts_dir: artifacts 
 
data_ingestion_config:
  # URL to download the dataset from, which is a ZIP file containing book data.
  dataset_download_url: https://github.com/entbappy/Branching-tutorial/raw/master/books_data.zip
  #  Directory where the dataset will be extracted or stored, here "dataset".
  dataset_dir: dataset
  # Directory where the ingested (processed or prepared) data will be saved, "ingested_data".
  ingested_dir: ingested_data
  # Directory for raw data before processing, "raw_data".
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: cean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX_Books.csv
  ratings_csv_file: BX-Book-Ratings.csv

data_transformation_config:
  transformed_data_dir: transformed_data

model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl

recommendation_config:
  poster_api_url: https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US
